### ISSUE TITLE
Recepies for the some of the Obsidiantools seems to be wrong or Broken

### ISSUE THREAD

**Issue by ghost** [Krxwallo/ObsidianExtension#1]
Just to your knowledge
![2020-08-01 (2)](https://user-images.githubusercontent.com/17672848/89108276-4f7b6c80-d437-11ea-8463-89d094f380a8.png)
![2020-08-01 (3)](https://user-images.githubusercontent.com/17672848/89108290-75a10c80-d437-11ea-88a5-a02153b422a2.png)

the version is 1.6.0

**Comment by Krxwallo** [comment]
Thanks, I fixed it: https://github.com/Krxwallo/ObsidianExtension/commit/01a12aa6d84ee746c364456bcef1c1fcc3c2843e
